Implementation of Python Basic Libraries such as Statistics, Math, Numpy
and Scipy:-
a) Usage of methods such as floor(), ceil(), sqrt(), isqrt(), gcd() etc.
b) Usage of attributes of array such as ndim, shape, size, methods such as
sum(), mean(), sort(), sin() etc.
c) Usage of methods such as det(), eig() etc.
d) Consider a list datatype(1D) then reshape it into2D, 3D matrix using
numpy
e) Generater and ommatrices using numpy
f) Find the determinant of a matrix using scipy
g) Find eigen value and eigen vector of a matrix using scipy



In [2]:
import math

# Example numbers
x = 7.8
y = 16

print("Number:", x)
print("math.floor(x):", math.floor(x))   # Largest integer <= x
print("math.ceil(x):", math.ceil(x))     # Smallest integer >= x
print("math.sqrt(y):", math.sqrt(y))     # Square root (float)
print("math.isqrt(y):", math.isqrt(y))   # Integer square root
print("math.gcd(12, 18):", math.gcd(12, 18))  # Greatest Common Divisor
print("math.factorial(5):", math.factorial(5))  # Factorial of 5


Number: 7.8
math.floor(x): 7
math.ceil(x): 8
math.sqrt(y): 4.0
math.isqrt(y): 4
math.gcd(12, 18): 6
math.factorial(5): 120


In [3]:
import numpy as np

# Create a NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("ndim (number of dimensions):", arr.ndim)
print("shape (rows, cols):", arr.shape)
print("size (total elements):", arr.size)

# Common methods
print("Sum of all elements:", arr.sum())
print("Mean of all elements:", arr.mean())
print("Sorted array (flattened):", np.sort(arr, axis=None))
print("Sine of each element (in radians):\n", np.sin(arr))


Array:
 [[1 2 3]
 [4 5 6]]
ndim (number of dimensions): 2
shape (rows, cols): (2, 3)
size (total elements): 6
Sum of all elements: 21
Mean of all elements: 3.5
Sorted array (flattened): [1 2 3 4 5 6]
Sine of each element (in radians):
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [4]:
# For determinant and eigenvalues, use numpy or scipy
from numpy.linalg import det, eig

matrix = np.array([[2, 1],
                   [1, 2]])

print("Matrix:\n", matrix)
print("Determinant:", det(matrix))

eigenvalues, eigenvectors = eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Matrix:
 [[2 1]
 [1 2]]
Determinant: 2.9999999999999996
Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [5]:
# Original 1D list
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9]

arr = np.array(lst)
print("Original 1D Array:", arr)

# Reshape into 2D (3 rows, 3 columns)
arr_2d = arr.reshape(3, 3)
print("\n2D Array (3x3):\n", arr_2d)

# Reshape into 3D (1 block, 3 rows, 3 columns)
arr_3d = arr.reshape(1, 3, 3)
print("\n3D Array (1x3x3):\n", arr_3d)


Original 1D Array: [1 2 3 4 5 6 7 8 9]

2D Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

3D Array (1x3x3):
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [6]:
zeros_matrix = np.zeros((3, 3))
ones_matrix = np.ones((2, 4))
identity_matrix = np.eye(3)  # Identity matrix

print("3x3 Zero Matrix:\n", zeros_matrix)
print("\n2x4 Ones Matrix:\n", ones_matrix)
print("\n3x3 Identity Matrix:\n", identity_matrix)


3x3 Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

2x4 Ones Matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
from scipy import linalg

A = np.array([[4, 2],
              [3, 1]])

det_A = linalg.det(A)
print("Matrix A:\n", A)
print("Determinant of A (using SciPy):", det_A)


Matrix A:
 [[4 2]
 [3 1]]
Determinant of A (using SciPy): -2.0


In [8]:
# Eigenvalue & Eigenvector using SciPy
eigenvalues, eigenvectors = linalg.eig(A)

print("Eigenvalues (SciPy):", eigenvalues)
print("Eigenvectors (SciPy):\n", eigenvectors)


Eigenvalues (SciPy): [ 5.37228132+0.j -0.37228132+0.j]
Eigenvectors (SciPy):
 [[ 0.82456484 -0.41597356]
 [ 0.56576746  0.90937671]]
